<template>
  <div class="settings-workspace">
    <div class="settings-search"><el-input :value="query" clearable prefix-icon="el-icon-search" placeholder="搜索名称、配置键或说明" aria-label="搜索配置" @input="$emit('search', $event)" /><span>{{ query.trim() ? `${groups.reduce((sum, item) => sum + item.count, 0)} 个匹配项` : '按分类查找与调整配置' }}</span></div>
    <div class="settings-body">
      <nav class="settings-nav" aria-label="配置分类"><button v-for="group in groups" :key="group.key" type="button" :class="{ selected: value === group.key && !query.trim() }" :aria-current="value === group.key && !query.trim() ? 'page' : null" @click="$emit('search', ''); $emit('input', group.key)"><i :class="group.icon || 'el-icon-setting'"></i><span>{{ group.title }}</span><small>{{ group.count }}</small></button><slot name="nav" /></nav>
      <main class="settings-content"><slot /><div v-if="query.trim() && !groups.some(item => item.count)" class="settings-empty"><i class="el-icon-search"></i><h3>没有匹配的配置</h3><p>试试名称、英文配置键或简短关键词。</p></div></main>
    </div>
    <footer class="settings-save"><slot name="footer" /></footer>
  </div>
</template>
<script>
export default { name: 'SettingsLayout', props: { value: { type: String, default: '' }, query: { type: String, default: '' }, groups: { type: Array, default: () => [] } } }
</script>
<style scoped>
.settings-workspace { max-width:1600px; margin:0 auto; min-width:0; padding:24px; background:var(--bg-color-secondary,#fff); border:1px solid var(--border-color-light); border-radius:14px; color:var(--text-color,#253247); }.settings-search { display:flex; gap:20px; align-items:center; padding:8px 0 24px; }.settings-search .el-input { max-width:460px; }.settings-search > span { color:var(--text-color-secondary,#758090); font-size:12px; }.settings-body { display:grid; grid-template-columns:200px minmax(0,1fr); gap:28px; align-items:start; }.settings-nav { position:sticky; top:20px; display:flex; flex-direction:column; gap:5px; padding:8px; border-radius:12px; background:var(--bg-color-secondary,#f6f8fb); }.settings-nav button { display:flex; align-items:center; gap:10px; min-height:44px; text-align:left; padding:10px 12px; border:0; border-radius:8px; background:transparent; color:var(--text-color-secondary,#758090); cursor:pointer; font:inherit; font-size:13px; }.settings-nav button:hover { background:var(--bg-color,#fff); }.settings-nav button.selected { color:var(--primary-color,#5c83d6); background:var(--bg-color,#fff); box-shadow:0 2px 8px #25324708; font-weight:600; }.settings-nav button span { flex:1; white-space:nowrap; }.settings-nav small { font-size:10px; opacity:.7; }.settings-content { min-width:0; padding:6px 24px 18px; border-left:1px solid var(--border-color-light); background:transparent; }.settings-content ::v-deep .settings-group-heading { display:flex; gap:12px; align-items:center; padding:20px 0 16px; border-bottom:1px solid var(--border-color-light,#e9edf2); }.settings-content ::v-deep .settings-group-heading h3 { margin:0; font-size:18px; font-weight:600; }.settings-content ::v-deep .settings-group-heading p { margin:6px 0 0; font-size:12px; line-height:1.7; color:var(--text-color-secondary,#758090); }.settings-content ::v-deep .settings-group-heading > div { flex:1; min-width:0; }.settings-save { display:flex; align-items:center; justify-content:flex-end; gap:10px; position:sticky; bottom:0; z-index:5; padding:16px 20px; margin-top:24px; background:var(--bg-color,#fff); border:1px solid var(--border-color-light,#e9edf2); border-radius:12px; box-shadow:0 -5px 20px #25324705; }.settings-save ::v-deep .save-description { margin-right:auto; color:var(--text-color-secondary,#758090); font-size:12px; line-height:1.6; }.settings-save ::v-deep .save-description strong { display:block; color:var(--text-color,#253247); font-weight:500; }.settings-empty { text-align:center; padding:65px 12px; color:var(--text-color-secondary,#758090); font-size:13px; }.settings-empty i { font-size:26px; }button:focus-visible { outline:2px solid var(--primary-color,#5c83d6); outline-offset:2px; }
@media(max-width:768px) { .settings-workspace { padding:12px; }.settings-content { border-left:0; } .settings-body { grid-template-columns:minmax(0,1fr); gap:16px; }.settings-nav { position:static; flex-direction:row; overflow-x:auto; max-width:100%; }.settings-nav button { flex:none; }.settings-search { padding-bottom:16px; gap:8px; flex-direction:column; align-items:stretch; }.settings-search .el-input { max-width:none; }.settings-content { padding:0 16px 16px; }.settings-save { flex-wrap:wrap; padding:12px; gap:8px; }.settings-save ::v-deep .save-description { flex-basis:100%; }.settings-save ::v-deep .el-button { margin-left:0; }.settings-content ::v-deep .settings-group-heading { padding-top:20px; } }
</style>
